# Loops are used when we have do same work repetadely
# Python loops are of two types:
# 1. for loop
# 2. while loop

# Unlike C language where loops are of three types:
# 1. for loop                                           # pre-check
# 2. while loop                                         # pre-check
# 3. do-while loop (which is not present in Python)     # post-check

# Unlike C language where for loop is used with counter variable(iterator)
# In Python for loop is used to iterate over a sequence (like list, tuple, string, etc.)

# Note: Always be caution while using loops to avoid infinite loops.

# Example of while loop with iterator(i):
i = 1
while i <= 5:
    print(f'Iteration number: {i}')
    i += 1   # Incrementing the iterator   
print('While loop ended.\n')


# Decending order:
i = 6
while i >= 1:
    print(f'Iteration number: {i}')
    i -= 1   # Decrementing the iterator   
print('While loop ended.\n')  


# WAP to print the multiplication table of a given number using while loop
num = int(input(f'Enter a number to print its multiplication table: '))
i = 0
while i <= 10:
    mul = num * i
    print(f'{num} × {i} = {mul} ')
    i += 1


# Print the elements of the following list using a loop
# [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
num = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
i = 1
while i <= len(num):
    print(f'Number at {i}: {num[i-1]}')
    i += 1


# Search for a number 'X' in this tuple  using loop:
# (1, 4, 9, 16, 25, 36, 49, 64, 81, 100)
num = (1, 4, 9, 16, 25, 36, 49, 64, 81, 100)
print(f'Given tuple: {num}')
x = int(input(f'\nEnter a number to search in the given tuple: '))
i = 1
isPresent = False

while i <= len(num):
    # print(f'{x} is not found in the given tuple') if ( x != num[i-1] ) else print(f'{x} is found at index {i-1} in the given tuple')
    if x == num[i-1]:
        print(f'Given number "{x}" is included in the list at index "{i}"\n')
        isPresent = True
        break    
    i += 1

if isPresent == False:
    print(f'Given number "{x}" is exclusive from the given list.\n')


# Talking about this solution:
# Using while loop wasn't the best way to search for an element in a tuple or list.
# It would be better to use 'for loop' for such tasks in Python.
num = (1, 4, 9, 16, 25, 36, 49, 64, 81, 100)
print(f'Given tuple: {num}')
x = int(input(f'\nEnter a number to search in the given tuple: '))

idx = 0
for value in num:
    idx += 1
    if x == value:
        print(f'Given number "{x}" is included in the list at index "{idx}"\n')
        break
else:
    print(f'Given number "{x}" is exclusive from the given list.\n')

# Conclusion: Using for loop is more Pythonic and efficient for such tasks.








# What is the difference between for loop in Python and in C?

# In C, for loop is primarily used with a counter variable to iterate a specific number of times.
# In Python, for loop is used to iterate over elements of a sequence (like list, tuple, string, etc.) 
# directly without needing a counter variable.

# The primary difference is that a C for loop is a condition-controlled loop using an index variable, whereas a Python for loop is an iterator-based loop (a "for-each" loop) that iterates directly over items in a sequence. 

# Key Differences
# Feature 	                                     C for Loop	                                                                  Python for Loop
# Type of Iteration	          - Condition-controlled (definite iteration)	                               - Iterator-based (iterates over a sequence)
# Syntax	                  - for (initialization; condition; increment)	                               - for iterating_var in sequence:
# Control Variable            -	An index variable that can be explicitly modified within                   - A variable that gets a new value assigned to it from the iterable at the start of each iteration;
#                               the loop body to affect the next iteration.	                                 changes within the loop body are lost in the next cycle.
# Explicit Control	          - Requires explicit initialization, condition checking, and                  - Manages iteration automatically using the iterator protocol, abstracting away index management.
#                               increment/decrement logic.	
# Data Types	              - Typically used with basic data types and arrays using explicit indexing.   - Works with any iterable object, such as lists, tuples, strings, or dictionaries.


# Examples
# C Example: This loop runs based on a condition and manual incrementing.
# int i;
# for (i = 0; i < 5; i++) {
#     printf("%d", i);
# }
# // Output: 01234


# Python Example: This loop iterates over a sequence generated by range() (which acts as an iterable).
# for i in range(5):
#     print(i)
# # Output: 0, 1, 2, 3, 4 (each on a new line)

# In Python, the for loop is designed for readability and convenience by handling the mechanics of iteration internally, while the C for loop offers more granular, manual control over the looping process. 





# Flow control statements in Control Structures:
# 1. break statement            - Terminates the loop entirely
# 2. continue statement         - Skips the current iteration and moves to the next iteration
# 3. pass statement             - Does nothing, acts as a placeholder

# Example of pass statement:
# for i in range(1,6):
#     if i == 3:
#         pass    # Placeholder for future code
#     print(i)





# range() function in Python:
# Range functions returns a sequence of numbers, starting from 0 by default, and increments by 
# 1 (by default), and stops before a specified number.

# Syntax: range(start?, stop, step?)
# By default: range(0, stop, 1 )


# Example of range() function:
for i in range(5):  #range(0, 5, 1)  - 0 to 4, 5 is excluded
    print(i)

for i in range(1, 5):  #range(1, 5, 1) - 1 to 4, 5 is excluded
    print(i)

for i in range(1, 10, 2):  #range(1, 10, 2)  - 1 t0 9, 10 is excluded, step is 2.
    print(i)

for i in range(10, 0, -1):  #range(10, 0, -1)  - 10 to 1, 0 is excluded, step is -1.
    print(i)



# Note: range() function returns a range object, which is an immutable sequence type.
# As for loop traverses through the list or sequence, here, the range function generates akind of list to traverse through.
print(type(range(5)))  # <class 'range'>



# Print the numbers from 1 to 100 using range() function and for loop
for num in range(1, 101, 1):
    print(f'Number: {num}')


# Print numbers from 100 to 1:
for num in range(100, 0, -1):
    print(f'Number: {num}')


# WAP to print the multiplication table of a given number using while loop
num = int(input(f'Enter a number to print its multiplication table: '))
for i in range(0, 11, 1):
    mul = num * i
    print(f'{num} x {i} = {mul}')

# WAP to find the sum of first n natural numbers using while loop:
num = int(input(f'Enter a number upto where sum is to be calculated: '))
total = 0
for i in range(1, num + 1, 1):
    total += i
print(f'Sum upto the given number is {total}')


# WAP tp find the factorial of first n numbers using for loop:
num = int(input(f'Enter a number to find its factorial: '))
fac = 1
for i in range(num, 1, -1):
    fac *= i
print(f'Factorial of the given number is {fac}')
