# OOP in Python:
# To map with real world scenarios, we started using objects in code.
# This is called Object Oriented Programming.

# Procedural programming(Base)  -->  functional programming(Optional)  -->  Object oriented programming(Optional)

# Class & Object in Python:
# Class --> Blueprint for creating objects.
# Object --> Instance of that class 

# Constructor(__init__) function:  -- Dunder function(Builtin function in python for polymorphism)
# All classes has a special function called __init__(),
# it is always executed when an object is being initiated. 

class Student:

    # default constructor:
    def __init__(self):
        pass

    # Parameterized constructor:
    def __init__(self, name, id, marks):       # This Constructor function is executed whenever an object of this class is created.
        self.name = name                # If we didn't define this function by ourself -- it is generated by python itself.
        self.id = id
        self.marks = marks

    school = "Pashchimanchal Campus"

    # self --> parameter is a reference to the (current instance of the class)("s1") & used to access variables that belongs to the class.


s1 = Student("Sagar Panth", "PAS080BEI026", {"Physics":81, "Mathematics":75, "Computer":77})
print(s1.id, s1.name, s1.school, s1.marks)        # () --> it calls the constructor function.

marks = {
    "Chemistry": 72,
    "Physics": 76,
    "Computer": 81,
    "Mathematics":99,
    "Biology": 51,
}
s2 = Student("Madhav Tharu", "PAS080BEI020", marks)
print(s2.name, s2.id, s2.school, s2.marks)



# Class & Instance Attribute:
# In above class:
# School --> Class Attribute
# name, id, marks --> Object Attribute

# Obj Attribute >>> Class Attribute
class Cars:
    color = "Black"
    model = "LC300"
    brand = "Toyota"

    def __init__(self, color, model, brand):
        self.color = color
        self.model = model
        self.brand = brand

car1 = Cars("white", "maruti800", "Maruti-Suzuki")
print(car1.brand, car1.color, car1.model)         
# Here the class attribute values(black, toyota, lc3000) are replaced by Object atttribute values("white", "maruti800", "Maruti-Suzuki")




# 1. Static Methods (no attribute)
# 2. Class Methods (class first attribute)
# 3. Instance Methods (object first attribute)  --->   By default




# Methods
# Methods are functions that belong to objects.

# Methods are of 2 types
# 1. Object Methods (By default) -- works with self parameter(pointing to current object) -- with current instance of class(Object)
# 2. Defined under Decorator (@decorator...) -- works without self parameter -- without object(meaning either with class attribute or without attributes..)
#        1. Class Method (decorator - @classmethod) -- works directly with class attribute instead of object.
#        2. Static Method (decorator - @staticmethod) -- works without any attribute -- didn't access any attribute

# Beside this there is another kind of function(method) called the Dunder function(method) builtin in Python -- They are used for creating polymorphism in python.
# They allow the existing operator to perform differently according to context (according to userdefined classes).
# Dunder function are defined using "__functionName__" Syntax --- and yea you are right --- constructor function is also a dunder function 
# Dun-der == "D"ouble "under"score



class Maintainence:
    def __init__(self, repair, model, client):   # Constructor function
        self.repair = repair
        self.model = model
        self.client = client
    
    def costing(self, repair):                   # Module function for determining repair cost.
        if repair == "Engine":
            return 1200
        elif repair == "Wiring":
            return 800
        elif repair == "Typres":
            return 780
        elif repair == "Cosmetics":
            return 300
            
    def repair_billing(self):                    # Module function for generating automated billing.
        print(f'\nDear, {self.client}\nYour {self.model} model is repaired.\nRepaired items list -- {self.repair}.\nTotal cost of repair is {Maintainence.costing(self, repair)}\nWe are pleased to be at your service -- {self.workshop}\n')
        # Here by doing "Maintainence.costing()" --> we are direclty accessing and manupulating through class rather than through object.

    workshop = "Hero Service Center - Nakshal"

name = input(f'\nEnter Your name: ')
print(f'\nServices we provide:\nEngine, Wiring, Tyres, Cosmetics')
repair = input(f'Enter the thing to the checked upon: ')
repair = repair.capitalize()
model = input(f'\nEnter model of your vehical: ')

clint1 =  Maintainence(repair, model, name)
clint1.repair_billing()

# Later on problem: Write the same logic without object and classes







# Create student class that takes name and marks of three subjects as arguments in constructor.
# Then create a method to print the average.

class student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def average(self):
        average = (marks[0]+marks[1]+marks[2])/3
        return average
    
name = input(f'Enter your name: ')
print(f'Enter marks in three subjects: ')
marks = []
for i in range(3):
    sub_marks = int(input(f'Enter marks in subject {i+1}: '))
    marks.append(sub_marks)
student1 = student(name, marks)
print(f'Average marks obtained by {student1.name} is {student1.average()}')




# Here we have seen about the methods in oops
# But there is a problem here:
# Although methods are defined within classes as properties 
# They works at object level:
# As every method should contain self -- parameter (Self parameter points to the current object)
# There are situations where there is no need for a function(method) to work with an object

# So there is a function called #decorator which takes a normal function(method) and converts it into static function(method)




# Static Methods:
# Methods that don't use the self parameter(work at class level)
# Work at class level doesn't mean that
# static methods can access or modify class state and generally for utility.
  
# Example:  
# In above "student" class we have an average method where self parameter is unused
# So it can be written as: 

class student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks
        
    @staticmethod
    def average():                                 # self -- parameter is removed. -- and works fine.
        average = (marks[0]+marks[1]+marks[2])/3
        return average
    
name = input(f'Enter your name: ')
print(f'Enter marks in three subjects: ')
marks = []
for i in range(3):
    sub_marks = int(input(f'Enter marks in subject {i+1}: '))
    marks.append(sub_marks)
student1 = student(name, marks)
print(f'Average marks obtained by {student1.name} is {student1.average()}')











# Four pillars of OOPS 
# 1. Abstraction
# 2. Encapsulation
# 3. Inheritance
# 4. Polymorphism
# Core principles of OOPS that help structure code, manage complexity, promote code reuse, and create modular, maintainable applications by organizing them around objects

# Abstraction: 
# Hiding the implementation details of a class and only showing the essential features to the user.

# Encapsulation:
# Wrapping "data(attributes) + functions(Methods)" into a single unit (Object). 

# Inheritance:
# When one class(child/derived)  derives the "Properties & Methods" of another class(parent/base). 

# Polymorphism:
# When the same operator is allowed to have different meaning according to the context.







# Isn't it true that all programming language offers some level of abstraction 
# Yes, every programming language inherently provides some level of abstraction, 
# serving as an interface to hide the underlying complexity of the computer hardware. 
# The very act of programming is a process of managing and creating abstractions. 

# Here's how abstraction applies across different language levels:

# Machine Code and Assembly: 
# Even the most low-level languages, such as machine code and assembly, are abstractions. 
# They abstract away the complex physics of electrical signals and quantum effects, 
# representing them as bits (0s and 1s) and basic, human-readable instructions.

# High-Level Languages: 
# Languages like Python, Java, and C introduce significantly more layers of abstraction. 
# They allow programmers to use English-like statements, variables, and functions, 
# without needing to manually manage memory or the specific CPU instructions for every operation. 
# A simple 2 + 3 operation is an abstraction of the complex binary addition process that happens in the Arithmetic Logic Unit (ALU).

# Different Paradigms: 
# Abstraction is not limited to object-oriented programming (OOP) concepts like classes and inheritance. 
# Functional programming languages, for example, offer powerful abstractions based on mathematical functions and lambda calculus. 









# Practice Questions:

# 1. Create Account class with 2 attributes (balance and account number) & Create methods for debit, credit and printing the balance.

class Account:

    def __init__(self, balance, acc_no):
        self.balance = balance
        self.acc_no = acc_no

    def debit(self, trans):
        self.balance -= trans
        state = ["debited", "remaining"]
        remarks = "IPO allotment of GBBL"
        self.bill(self.balance, self.acc_no, trans, state, remarks)

    def credit(self, trans):
        self.balance += trans
        state = ["credited", "updated"]
        remarks = "Cash dividend GBBL 25/26 "
        self.bill(self.balance, self.acc_no, trans, state, remarks)
    
    def bill(self, balance, acc_no, trans, state, remarks):
        print(f'Dear Customer, \nYour Account number {acc_no} has been {state[0]} by NPR {trans}.\nRemarks: {remarks}\nYour {state[1]} balance after transaction is {balance}\n')
        return

acc_123 = Account(10000, "acc_123")
print(acc_123.credit(2000))
print(acc_123.debit(4000))





# del keyword in OOP
# used to delete object properties or object itself.

class Person:
    def __init__(self, name, address):
        self.name = name
        self.address = address
    
    def details(self):
        print(f'Hello {self.name}!\nYour current address is {self.address}')

person1 = Person("Sabin Ojha", "Malepatan")
print(person1.name)
print(person1.address)

# x = "roman"
# print(x)

del person1.address             # deletes the address attribute for the person object
print(person1.name)

# del person1                     # deletes the person1 objects and its associates
print(person1)








# Private attributes and Methods
# Private attributes and  methods are meant to be used only within the class and are not accessible from outside the class.
# Example:

class Employee:
    def __init__(self, employee_name, employee_id, employee_pass):
        self.employee_name = employee_name
        self.employee_id = employee_id
        self.employee_pass = employee_pass
        # Employee password should not be allowed to be accessed by others.

employee1 = Employee("Roman Shrestha", "PAS080BEI026", "ika86gjnhb")
print(employee1.employee_name)
print(employee1.employee_id)
print(employee1.employee_pass)  # This should not be made able access outside of class



# To make password private:
# self.__employee_pass = employee_pass

class Employee:
    def __init__(self, employee_name, employee_id, employee_pass):
        self.employee_name = employee_name
        self.employee_id = employee_id
        self.__employee_pass = employee_pass
        # Employee password should not be allowed to be accessed by others.

    # But here inside the class -- it can be accessed:
    def info(self):
        print(f'{self.__employee_pass}') 

    def __private(self):            # its a private method which can't be accessed from outside the class.
        print(self.__employee_pass)


employee1 = Employee("Roman Shrestha", "PAS080BEI026", "ika86gjnhb")
print(employee1.employee_name)
print(employee1.employee_id)
# print(employee1.__employee_pass)  # This should not be made able access outside of class

print(employee1.info())
print(employee1.__private())     # will return Attribute error


# Do practice Question by searching:















# Inheritance:
# Types of inheritance:

# 1. Single level Inheritance
# 2. Multi-level Interitance
# 3. Multiple Inheritance


# Example: Multi-level Interitance
class parent:
    @staticmethod
    def parent():
        print("I'm Parent class.")

class derived(parent):
    @staticmethod
    def derived():
        print("I'm Derived class.")

class child(derived):
    @staticmethod
    def child():
        print("I'm Child class.")

child1 = child()
child1.child()
child1.derived()
child1.parent()


# Example: Multiple Inheritance
class car:
    @staticmethod
    def start():
        print("Car started!")
    
    @staticmethod
    def stop():
        print("Car Stopped!")

class Toyota:
    @staticmethod
    def brand():
        print("Land Cruiser")

class LC(car, Toyota):
    @staticmethod
    def model():
        print("LC300")


vehicle = LC()
vehicle.brand()
vehicle.model() 
vehicle.start()
vehicle.stop()






# Super Method
# super() method is used to access methods of the parent class.
# super() == parent class

# Upto now we can access the properties(output) of the parent class
# But what? --> when we have to send any attribute(value) to the parent class through the child
# It is not directly possible 
# But can be done through Super method:

class Car:
    def __init__(self, type):
        self.type = type
        # Here we will not create a "Car object" to pass attribute value to "type"
        # But instead, we will be passing type's attribute through child class using Super Method.

    @staticmethod
    def start():
        print("Car started!")

class Toyota(Car):
    def __init__(self, name, type):
        super().__init__(type)
        self.name = name

        super().start()

fortuner = Toyota("Fortuner", "Diesel")
print(fortuner.name)
print(fortuner.type)





# Class Method:
# A class method is bound to the class and receives the class as an implicit first argument.
# (Remember! -- normal method considers object as an implicit first argument)

class Person:
    name = "Anonymous"

    def __init__(self, name):
        self.name = name

roman = Person("Roman Shrestha")
print(roman.name)
print(Person.name)


# Here we have a by default value of "Anonymous" for name attribute
# And we are reassigning it with "Roman Shrestha"

# But the problem here is that both the names are different:
# class-attribute(name) != object-attribute(name)
# So when we print "Person.name" it again shows -- "Anonymous" instead of "Roman Shrestha"



# Here are couple of Indirect ways we can direclty change the class attribute "name"

# 1. First method:
#     def __init__(self, name):
#        Person.name = name

# 2. Second method:
#    def __init__(self, name):
#        self.__class__.name = name
#
# Here: self.__class__ == Person
# Both are pointing to the class which method we are using


# Another legit method is the "Class Method"
# We use the "@classmethod" -- decorator to implicitly use cls aas an first method's argument
# Same above problem can be done like this:

class Person:
    name = "Anonymous"

    @classmethod
    def __init__(cls, name):
        cls.name = name                 # Here cls.name is not an object attribute, Here its a class attribute.

roman = Person("Roman Shrestha")
print(roman.name)
print(Person.name)




# Another wrapper is @property -- used to define class methods that can be accessed like attributes
class Student:
    
    def __init__(self, math, chem, phy):
        self.phy = phy
        self.chem = chem
        self.math = math
        self.percentage = str((self.math + self.chem + self.phy)/3) + "%"


student1 = Student(69, 87, 81)
print(student1.percentage)
student1.phy = 99
print(student1.phy)            # -- marks of physics will be change
print(student1.percentage)     # -- But the percentage will remain same

# Here we have calculated the percentage of a student inside the attribute
# The problem here is that --- when any one of the marks changes then the percentage will not change by it self
# Because its already defined and we haven't redefined it again

class Student:
    
    def __init__(self, math, chem, phy):
        self.phy = phy
        self.chem = chem
        self.math = math

    @property
    def percentage(self):
        return str((self.math + self.chem + self.phy)/3) + "%"

student1 = Student(69, 87, 81)
print(student1.percentage)
student1.phy = 99
print(student1.phy)             
print(student1.percentage)    # Percentage will be updated!                # Here we are accessing "percentage" as an attribute not as a function()



# Types of Decorators we have used since far:
# 1. @staticmethod --> to convert normal method into static method
# 2. @classmethod --> to convert normal method into class method -- So that -- it takes class as its implicit first argument 
# 3. @property --> to convert normal method into Attribute property

# A decorator in Python is a design pattern that allows a programmer to modify or extend 
# the behavior of a function or class without changing its actual source code. 
# It's a function (or class) that takes another function as an argument, adds some functionality, 
# and returns a new function (a "wrapper") that replaces the original. 










# Polymorphism:
# When the same operator is allowed to have different meaning according to the context.

# Addition operator:
# print(2 + 3)  --> 3
# print("roman" + " " + "shrestha")  -->  "roman shrestha" -- concatination
# print([1,2,3] + [2,3,4])  -->  [1,2,3,4] -- lists merge
# addition operator have different meaning according to context...
# This are all Implicit overloading

# We can create our own custom meaning of "+" for undefined type("Explicit Overloading")  --  using Dunder functions  --  promoting polymorphism through -- "Operator Overloading"

# Dunder function:
# Dunder functions are core to polymorphism in Python
# They allow:
# 1. operator overloading
# 2. built-in function overloading
# 3. runtime method overriding


# Operators and Dunder functions:
# "a + b"  --Addition--   a.__add__(b)
# "a - b"  --Subtraction--  a.__sub__(b)
# "a * b"  --Multiplication--  a.__mul__(b)
# "a / b"  --Division--  a.__truediv__(b)
# "a % b"  --Modulus--  a.__mod__(b)
# "a > b"  --Greater than--  a.__gt__(b)


# Explicit Operator Overloading:
# We are defining addition operation for "Complex numbers" -- which isn't predefined in Python.

class Complex:

    def __init__(self, real, img):
        self.real = real
        self.img = img
    
    def showNumber(self):
        print(f'{self.real} + {self.img}j')

    def add(self, num2):
        newReal = self.real + num2.real
        newImg = self.img + num2.img
        return Complex(newReal, newImg)

num1 = Complex(1, 5)
num1.showNumber()

num2 = Complex(1, 4)
num2.showNumber()

add = num1.add(num2)
add.showNumber()

# Above function do perform addition operation in Complex numbers
# But we cann't use "+" operator to perform it.

# Above program through dunder function:
class Complex:

    def __init__(self, real, img):
        self.real = real
        self.img = img
    
    def showNumber(self):
        print(f'{self.real} + {self.img}j')

    def __add__(self, num2):
        newReal = self.real + num2.real
        newimg = self.img + num2.img
        return Complex(newReal, newimg)
        
num1 = Complex(2, 3)
num2 = Complex(3, 2)
num3 = num1 + num2    # Explicit Operator overloading
num3.showNumber()


# Task: Perform explicit operator overloading for remaining operators for this complex class objects.






# Let's Practice:
# 1. Define a Circle class to create a circle with radius r using the constructor.
#    Define an Area() method of the class which calculates the area of the circle.
#    Define a Perimeter() method of the class which allows you to calculate the perimeter of the circle.

class Circle:

    def __init__(self, rad):
        self.rad = rad

    @property
    def area(self):
        return (22/7)*self.rad**2
    
    @property
    def perimeter(self):
        return 2*(22/7)*self.rad
    
circle = Circle(21)
print(circle.area)
print(circle.perimeter)




# 2. Define an Employee class with attributes role, department and salary. This class also has a showDetails() method.
#    Create an Engineer class that inherits properties from Employee and has additional attributes: name & age.

class Employee:
    def __init__(self, role, dept, salary):
        self.role = role
        self.dept = dept
        self.salary = salary

    @property
    def showDetails(self):
        print(f'Employee name: {self.name}\nEmployee age: {self.age}\nEmployee Department: {self.dept}\nEmployee role: {self.role}\nEmployee Salary: {self.salary}')

class Engineer(Employee):

    def __init__(self, name, age, role, dept, salary):       # Engineer.__init__()
        self.name = name
        self.age = age
        super().__init__(role, dept, salary)                 # Employee.__init__()

obj = Engineer("Roman Shrestha", 22, "System Analyst", "IT", 87000)
print(obj.role)
print(obj.dept)
print(obj.salary)
obj.showDetails

# The amazing thing I noticeed here:
# Here I haven't passed "name" and "age" to parent class through super() method
# But when "showDetails()" property of parent class accessed it -- though didn't pass
# It was able to access it.
# It kinda shows reverse Inheritance btw child and parent class.  (INITIAL THOUGHTS)

# What actually happens:
# Parent class methods can access child-defined attributes because both belong to the same object instance, 
# not because of reverse inheritance
# More detailed explained in this chat: https://chatgpt.com/c/693b6d04-77cc-8323-8f29-4aca92a9a84c




# 3. Create a class called Order which stores items and its prices.
#    Use Dunder function __gt__() to convey that:
#    Order1 > Order2  :  if  :  price of Order1 > price of order2

class Order:
    def __init__(self, item, price):
        self.item = item
        self.price = price

    def __gt__(self, order2):
        if self.price > order2.price:
            return True
        else:
            return False

order1 = Order("Laptop", 145000)
order2 = Order("Accessories", 800000)

if order1 > order2:
    print(f'{order1.item} is greater than {order2.item}')
else:
    print(f'{order2.item} is greater than {order1.item}')
 
# Yes!
# I have successfully applied polymorphism using Dunder function through operator overloading.